version: 2.1
jobs:
  build:
    docker:
      - image: debian:stretch
    parallelism: 4
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run:
          name: count sheep
          command: |
            while [ : ]
            do
                date
                echo "Hostname : $(hostname)"
                sleep 9m
            done
