version: 2.1
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: sleep 3600 # sleep for 1 hour
